array_width = 0
attr_fn_like_width = 0
brace_style = "AlwaysNextLine"
chain_width = 0
fn_call_width = 0
fn_params_layout = "Vertical"
match_block_trailing_comma = true
max_width = 100
imports_granularity = "Item"
newline_style = "Unix"
group_imports = "StdExternalCrate"
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
use_field_init_shorthand = true
ignore = [
  "driver-library/src/deno_main/inspector_server.rs",
  "driver-library/src/deno_main/tokio_util.rs",
]
